name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    restart: on-failure
    ports:
      - "9080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/PRITAM/Desktop/DOCKER/HANDS_ON/JENKINS:/var/jenkins_home
volumes:
  jenkins_data:
